name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/
          retention-days: 1

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build sensor-producer image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: sensor-producer
          push: false
          tags: iot-sensor-fleet/sensor-producer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build anomaly-detector image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: anomaly-detector
          push: false
          tags: iot-sensor-fleet/anomaly-detector:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max